### ISSUE TITLE
Can't scroll terminal window

### ISSUE THREAD

**Issue by AndrewMMcKinney** [adafruit/Adafruit-WebIDE#283] opened 2015-02-06 22:19 UTC
Chrome on OS X 10.10

**Comment by peterrus** [comment] 2015-03-22 21:37
duplicate of #280

**Comment by jwcooper** [comment] 2018-03-06 22:46
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!

**Closed by jwcooper** 2018-03-06 22:46 UTC
